//
// Created by romain on 16/07/24.
//

#ifndef GREEDYALGORITHM_VEHICLESHORTESTPATHCALCULATION_H
#define GREEDYALGORITHM_VEHICLESHORTESTPATHCALCULATION_H


class VehicleShortestPathCalculation {

};


#endif //GREEDYALGORITHM_VEHICLESHORTESTPATHCALCULATION_H
