//
// Created by romain on 16/07/24.
//

#ifndef GREEDYALGORITHM_VEHICLESHORTESTPATHCONTAINER_H
#define GREEDYALGORITHM_VEHICLESHORTESTPATHCONTAINER_H


class VehicleShortestPathContainer {

};


#endif //GREEDYALGORITHM_VEHICLESHORTESTPATHCONTAINER_H
