//
// Created by romain on 18/06/24.
//

#ifndef GREEDYALGORITHM_PTLINEGENERATIONPARAMETERS_H
#define GREEDYALGORITHM_PTLINEGENERATIONPARAMETERS_H


class PTLineGenerationParameters {

};


#endif //GREEDYALGORITHM_PTLINEGENERATIONPARAMETERS_H
